## Raman Tayal
## SID :- 18105075 

In [1]:
import pandas as pd
import numpy as np

### 1. Create Dataset

In [2]:
data = np.array([ [3.0, 22.0, 1.0, 3, 7.25, 0.0],
       [1.0, 38.0, 1.0, 4, 71.2833, 1.0],
       [3.0, 26.0, None, 5, 7.925, 1.0],
       [1.0, 35.0, 1.0, 6, 53.1, 1.0],
       [3.0, 35.0, 6, 7, 8.05, 0.0],
       [3.0, None, 7, 8, 8.4583, 0.0],
       [1.0, 54.0, 8, 9, 51.8625, 0.0],
       [3.0, 2.0, 3.0, 1.0, None, 0.0],
       [3.0, 27.0, 10, 2.0, 11.1333, 1.0],
       [2.0, 14.0, 1.0, 12, 30.0708, 1.0],
       [3.0, 4.0, 1.0, None, 16.7, 1.0],
       [1.0, 58.0, 13, 14, 26.55, 1.0],
       [3.0, 20.0, 14, 15, 8.05, 0.0],
       [3.0, 39.0, 1.0, 5.0, 31.275, 0.0],
       [3.0, 14.0, 16, 17, 7.8542, 0.0],
       [2.0, 55.0, 17, 18, 16.0, 1.0],
       [3.0, 2.0, 4.0, 1.0, 29.125, 0.0],
       [2.0, None, 19, 20, 13.0, 1.0],
       [3.0, 31.0, 1.0, 21, 18.0, 0.0],
       [3.0, None, 21, 22, 7.225, 1.0],
       [None, 35.0, 22, 23, 26.0, 0.0],
       [2.0, 34.0, 23, 24, 13.0, 1.0],
       [3.0, 15.0, 24, 25, 8.0292, 1.0],
       [1.0, 28.0, 25, 26, 35.5, 1.0],
       [3.0, 8.0, 3.0, 1.0, 21.075, 0.0],
       [3.0, 38.0, 1.0, 5.0, 31.3875, 1.0],
       [3.0, None, 28, 29, 7.225, 0.0],
       [1.0, 19.0, 3.0, None, 263.0, 0.0],
       [3.0, None, 30, 31, 7.8792, 1.0],
       [3.0, None, 31, 32, 7.8958, 0.0],
       [1.0, 40.0, 32, 33, 27.7208, 0.0],
       [1.0, None, 1.0, 34, 146.5208, 1.0],
       [3.0, None, 34, 35, 7.75, 1.0],
       [2.0, 66.0, 35, 36, 10.5, 0.0],
       [1.0, 28.0, 1.0, 37, 82.1708, 0.0],
       [1.0, 42.0, None, 38, 52.0, 0.0],
       [3.0, None, 38, 39, 7.2292, 1.0],
       [3.0, 21.0, 39, 40, 8.05, 0.0],
       [3.0, 18.0, 2.0, 41, 18.0, 0.0],
       [3.0, 14.0, 1.0, 42, 11.2417, 1.0],
       [3.0, 40.0, 1.0, 43, 9.475, 0.0],
       [2.0, 27.0, 1.0, 44, 21.0, 0.0],
       [3.0, None, 44, 45, 7.8958, 0.0],
       [2.0, 3.0, 1.0, 2.0, 41.5792, 1.0],
       [3.0, 19.0, 46, 47, 7.8792, 1.0],
       [3.0, None, 47, 48, 8.05, 0.0],
       [3.0, None, 1.0, 49, 15.5, 0.0],
       [3.0, None, 49, 50, 7.75, 1.0],
       [3.0, None, 2.0, 51, 21.6792, 0.0],
       [3.0, 18.0, 1.0, 52, 17.8, 0.0],
       [3.0, 7.0, 4.0, 1.0, 39.6875, 0.0],
       [3.0, 21.0, 53, 54, 7.8, 0.0],
       [1.0, 49.0, 1.0, 55, 76.7292, 1.0],
       [2.0, 29.0, 1.0, 56, 26.0, 1.0],
       [1.0, 65.0, 56, 1.0, 61.9792, 0.0],
       [1.0, None, 57, 58, 35.5, 1.0],
       [2.0, 21.0, 58, 59, 10.5, 1.0],
       [3.0, 28.5, 59, 60, 7.2292, 0.0],
       [2.0, 5.0, 1.0, 2.0, 27.75, 1.0],
       [3.0, 11.0, 5.0, 2.0, 46.9, 0.0],
       [3.0, 22.0, 62, 63, 7.2292, 0.0],
       [None, 38.0, 63, 64, 80.0, 1.0],
       [1.0, 45.0, 1.0, 65, 83.475, 0.0],
       [3.0, 4.0, 3.0, 2.0, 27.9, 0.0],
       [1.0, None, 66, 67, 27.7208, 0.0],
       [3.0, None, 1.0, 1.0, 15.2458, 1.0],
       [2.0, 29.0, 68, 69, 10.5, 1.0],
       [3.0, 19.0, 69, 70, 8.1583, 0.0],
       [3.0, 17.0, 4.0, 2.0, 7.925, 1.0],
       [None, 26.0, 2.0, 72, 8.6625, 0.0],
       [2.0, 32.0, 72, 73, 10.5, 0.0],
       [3.0, 16.0, None, 2.0, 46.9, 0.0],
       [2.0, 21.0, 74, 75, 73.5, 0.0],
       [3.0, 26.0, 1.0, 76, None, 0.0],
       [3.0, 32.0, 76, 77, 56.4958, 1.0],
       [3.0, 25.0, None, 78, 7.65, 0.0],
       [3.0, None, 78, 79, 7.8958, 0.0],
       [3.0, None, 79, 80, 8.05, 0.0],
       [2.0, 0.83, 80, 2.0, 29.0, 1.0],
       [3.0, 30.0, 81, 82, 12.475, 1.0],
       [3.0, 22.0, 82, 83, 9.0, 0.0],
       [3.0, 29.0, 83, 84, 9.5, 1.0],
       [3.0, None, 84, 85, 7.7875, 1.0],
       [1.0, 28.0, 85, 86, 47.1, 0.0],
       [2.0, 17.0, 86, 87, 10.5, 1.0],
       [3.0, 33.0, 3.0, 88, 15.85, 1.0],
       [3.0, 16.0, 1.0, 3.0, 34.375, 0.0],
       [3.0, None, 89, 90, 8.05, 0.0],
       [1.0, 23.0, 3.0, 2.0, 263.0, 1.0],
       [3.0, 24.0, 91, 92, 8.05, 0.0],
       [3.0, 29.0, 92, None, 8.05, 0.0],
       [3.0, 20.0, 93, 94, 7.8542, 0.0],
       [1.0, 46.0, 1.0, 95, 61.175, 0.0],
       [3.0, 26.0, 1.0, 2.0, 20.575, 0.0],
       [None, 59.0, 96, 97, 7.25, 0.0],
       [3.0, None, 97, 98, 8.05, 0.0],
       [1.0, 71.0, 98, 99, None, 0.0],
       [1.0, 23.0, 99, 1.0, 63.3583, 1.0],
       [2.0, 34.0, 100, 1.0, 23.0, 1.0],
       [2.0, 34.0, 1.0, 102, 26.0, 0.0]], dtype=object)

print(" Our data Looks as ( printing first 4 lines ) ")
print(data[0])
print(data[1])
print(data[2])
print(data[3])

 Our data Looks as ( printing first 4 lines ) 
[3.0 22.0 1.0 3 7.25 0.0]
[1.0 38.0 1.0 4 71.2833 1.0]
[3.0 26.0 None 5 7.925 1.0]
[1.0 35.0 1.0 6 53.1 1.0]


In [3]:
# lets first see how many nill values our data has 
cnt_null_values = 0

for i in range(100):
    for j in range(5):
        if data[i,j] == None:
            cnt_null_values += 1
print( "Total Null Values are : ", cnt_null_values)

Total Null Values are :  36


### 2. Perform standardization on the feature values without using sklearn.


In [4]:
for j in range(5):
    sum_of_coloumn = 0
    cnt_ = 0
    for i in range(100):
        if data[i,j] is not None:
            cnt_ += 1
            sum_of_coloumn += data[i,j]
    mean_of_column = sum_of_coloumn/cnt_
    for i in range(100):
        if data[i,j] is not None:
            data[i,j] -= mean_of_column
            data[i,j] = round(data[i,j],2)
            
print("Data after standarisation ( printing first 4 lines )")
print(data[0])
print(data[1])
print(data[2])
print(data[3])

Data after standarisation ( printing first 4 lines )
[0.59 -5.47 -32.03 -37.49 -22.46 0.0]
[-1.41 10.53 -32.03 -36.49 41.58 1.0]
[0.59 -1.47 None -35.49 -21.78 1.0]
[-1.41 7.53 -32.03 -34.49 23.39 1.0]


### 3. Replace the missing values in the features with the features’ mean value without using sklearn.


In [5]:
for j in range(5):
    sum_of_coloumn = 0
    cnt_ = 0
    for i in range(100):
        if data[i,j] is not None:
            cnt_ += 1
            sum_of_coloumn += data[i,j]
    mean_of_column = sum_of_coloumn/cnt_
    for i in range(100):
        if data[i,j] is None:
            data[i,j] = round(mean_of_column,2)
            
print("Data after replacing missing values ( printing first 4 lines )")
print(data[0])
print(data[1])
print(data[2])
print(data[3])

Data after replacing missing values ( printing first 4 lines )
[0.59 -5.47 -32.03 -37.49 -22.46 0.0]
[-1.41 10.53 -32.03 -36.49 41.58 1.0]
[0.59 -1.47 0.0 -35.49 -21.78 1.0]
[-1.41 7.53 -32.03 -34.49 23.39 1.0]


### 4. Perform classification (any classification technique) on this data. You can use sklearn for this task.


In [6]:
X = np.delete(data,obj = 5,axis = 1)
Y = np.delete(data, obj = (0,1,2,3,4), axis = 1)
X = X.flatten()
X = X.reshape(100,5)
print(X.shape,Y.shape)


(100, 5) (100, 1)


In [7]:
# For splitting of data into train and test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

from sklearn import preprocessing
from sklearn import utils

lab_enc = preprocessing.LabelEncoder()
y_train = lab_enc.fit_transform(y_train)
y_test = lab_enc.transform(y_test)



/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### 5. Print Scores of Model

In [8]:
# 1st we are using Logistic Regression
from sklearn.linear_model import LogisticRegression


model = LogisticRegression()
model.fit(X_train,y_train)


print(" Score using LogisticRegression :- ", +  model.score(X_test,y_test))

 Score using LogisticRegression :-  0.45


In [9]:
# 2nd we are using Support Vector Machines
from sklearn.svm import SVC

model2 = SVC()
model2.fit(X_train,y_train)

print(" Score using Support Vector Machines :- ", + model2.score(X_test,y_test))

 Score using Support Vector Machines :-  0.55


In [10]:
# 3rd Method
from sklearn.linear_model import SGDClassifier as SGC

model3 = SGC()
model3.fit(X_train,y_train)

print("Score using SGDClassifier :- ", + model3.score(X_test,y_test))

Score using SGDClassifier :-  0.4


In [11]:
from sklearn.neighbors import KNeighborsClassifier as KNN

# 4th Method

model4 = KNN()
model4.fit(X_train,y_train)

print( "Score using KNeighborsClassifier :- ", +model4.score(X_test,y_test))

Score using KNeighborsClassifier :-  0.45


GaussianNB implements the Gaussian Naive Bayes algorithm for classification. The likelihood of the features is assumed to be Gaussian

In [12]:
from sklearn.naive_bayes import GaussianNB as GNB

# 5th Method

model5 = GNB()
model5.fit(X_train,y_train)

print("Score using GaussianNB :- ", + model5.score(X_test,y_test))

Score using GaussianNB :-  0.65


In [13]:
from sklearn.tree import DecisionTreeClassifier as DTC

# 6th Method

model6 = DTC()
model6.fit(X_train,y_train)

print("Score using DecisionTreeClassifier :- ", + model6.score(X_test,y_test))

Score using DecisionTreeClassifier :-  0.6


In [14]:
from sklearn.neural_network import MLPClassifier as MLC

# 7th Method

model7 = MLC()
model7.fit(X_train,y_train)

print("Score using MLPClassifier :- ", +model7.score(X_test,y_test))

Score using MLPClassifier :-  0.5


/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [15]:
from sklearn.ensemble import RandomForestClassifier as RFC

# 8th Method

model8 = RFC()
model8.fit(X_train,y_train)

print("Score using MLPClassifier :- ", + model8.score(X_test,y_test))


Score using MLPClassifier :-  0.7
